# Generated by Django 2.2.16 on 2020-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=20)),
                ('mob', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
